name: Collect PR artifact

on:
  pull_request:
    types: [ opened ]

jobs:
  deploy:
    name: Collect PR artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Archive production artifacts
          uses: actions/upload-artifact@v2
          with:
            name: netlify-functions
            path: |
              functions
              netlify.toml
              package.json
              yarn.lock
            retention-days: 5
